version: "2"

networks:
  local-app:
    driver: bridge

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - local-app
    ports:
      - "27017:27017"
    command: "--smallfiles"
    
  mongo-seed:
    image: fvilers/mongo-seed:1.0.0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./seed-data:/seed-data
    command:
      "mongoimport --host mongo --port 27017 --db shapes --mode upsert --type json --file /seed-data/shapes.json --jsonArray"
    links:
      - mongo
    networks:
      - local-app

  node-server:
    image: "node:8"
    user: "node"
    working_dir: /server
    environment:
      - NODE_ENV=local
    volumes:
       - ./server:/server
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - server-variables.env
    networks:
      - local-app
    command: "npm start"
    links:
      - mongo

  node-client:
    image: "node:8"
    user: "node"
    working_dir: /client
    environment:
      - NODE_ENV=local
    volumes:
       - ./client:/client
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - local-app
    command: "npm start"